### ISSUE TITLE
GitHub release URL not found when installing - prebuild

### ISSUE THREAD

**Issue by fbede4** [MadLittleMods/node-usb-detection#140]
Hi,

I have tried to install the package via npm, but a got the following error:
    prebuild-install http 404 https://github.com/MadLittleMods/node-usb-detection/releases/download/v4.9.0/usb-detection-v4.9.0-electron-v87-win32-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=12.0.4 runtime=electron arch=x64 libc= platform=win32)

I dug through the release binaries here on github and the package mentioned above really does not exist. I have tried installing 4.10.0 and 4.9.0 versions, both threw similar exceptions.

Also, I realized, that npmjs only has the 4.10.0 release, not the newest 4.11.0.

Thanks in advance for any help

**Comment by fbede4** [comment]
Update: with earlier electron versions it seems to work, it only fails with the latest major release (12.x.x)

**Comment by MadLittleMods** [comment]
During the 4.11.0 release, I noticed that the prebuilds have been broken since 4.8.0 although there are around 100 prebuilds still available. But 4.11.0 tag had significantly less prebuilds so I decided on holding off publishing to npm, see https://github.com/MadLittleMods/node-usb-detection/pull/134

I still need to spend some more time to look at that PR and make the builds work again. Feel free to pick up the work and submit a PR if you're keen.

**Comment by MadLittleMods** [comment]
4.13.0 is now released to npm and [has all of the prebuilds available](https://github.com/MadLittleMods/node-usb-detection/releases/tag/v4.13.0) thanks to @mcous fixing up the CI, https://github.com/MadLittleMods/node-usb-detection/pull/152 🤘
